### ISSUE TITLE
Improve indexer/indexer-gateway performance

### ISSUE THREAD

**Issue by dzhelezov** [subsquid/hydra#44]
At the moment indexer-gateway can be taken down by large batch requests, such as 
```gql
query{
  substrateEvents(where: {section_eq: "staking", method_eq: "Reward", blockNumber_gt: 812681}, limit:5000) {
   blockNumber
   section
   method
   data
  }
}
```

Interestingly, the CPU load jumps to 99% and the server cannot handle subsequent request (and is eventually killed by the kubernetes orchestrator). A quick patch would to simply enforce small limits in the queries, but we should figure out how a more robust solution to make the indexer bullet-proof.

**Comment by eldargab** [comment]
## What is happening

A huge CPU / GC load is due to the fact, that warthog/type-graphql setup processes each field in the resulting payload asynchronously, even if all what is needed is to just to copy the value verbatim.

To prove the case I created the following script - https://gist.github.com/eldargab/9825ff1bb438f4f4fc2457ef105edd69.

To my surprise it did not perform as bad as I expected. That might be because actual warthog field resolution is much more complex and creates way more promises or because warthog's code is transpiled to ES.old and v8 has harder time optimising async stuff.

Nevertheless, above gist fully reproduces undesired behaviour, that is we see:

* High CPU load (200% on my machine)
* Excessive memory usage (Eats all available heap memory)
* Unresponsiveness during large request handling
* Similar profiling pictures

On other hand, during synchronous payload processing we see

* Moderate CPU load (no more than 70%)
* No problems with handling health check requests

## What can we do

Asynchronous field processing is triggered by type-graphql's middleware mechanism. All type-graphql middlewares are async by design and warthog installs one. 

We can:

1. Move away from type-graphql/warthog and get a huge performance boost anyway.
2. Work with type-graphql guys to add support for synchronous middlewares. Doesn't seem hard, but author might oppose such "complexity".
3. Maybe warthog can somehow get rid of its [DataLoaderMiddleware](https://github.com/goldcaddy77/warthog/blob/72fad57f9b5df20576286853416d60c24882e328/src/middleware/DataLoaderMiddleware.ts#L12).
4. MichalLytek/type-graphql#254 discussion suggests, that just recompilation of type-graphql to latest JavaScript version may bump performance by a factor of 2.

**Comment by eldargab** [comment]
The issue is solved by migration to hasura graphql server.
